In [11]:
import pandas as pd

In [16]:
df_reddit = pd.read_csv('C:/Users/cedua/CDIA - PUCSP/PROJETO PySpark - SAVINO/Contador-de-palavras---PySpark/data/final_data_socials/Contagem_reddit.csv')
df_reddit.drop(['Unnamed: 0'], axis=1, inplace=True)
df_reddit = df_reddit.rename(columns={"0":"words", "1": "count"})
df_reddit.head(20)

        words  count
0     protein    610
1      powder    190
2        whey    110
3        good     54
4       shake     43
5     isolate     42
6      shakes     35
7        bars     30
8     powders     28
9      weight     25
10  nutrition     25
11        bar     25
12       much     25
13      taste     24
14     anyone     23
15         vs     23
16       like     23
17       best     22
18     intake     22
19        get     22

In [19]:
df_twitter = pd.read_csv('C:/Users/cedua/CDIA - PUCSP/PROJETO PySpark - SAVINO/Contador-de-palavras---PySpark/data/final_data_socials/Contagem_Twitter.csv')
df_twitter.drop(['Unnamed: 0'], axis=1, inplace=True)
df_twitter = df_twitter.rename(columns={"Palavra":"words", "Frequência": "count"})
df_twitter = df_twitter.sort_values('count', ascending=False)
df_twitter.head(20)

          words  count
67     crossfit   3403
33         whey   2675
6        treino   2358
48      protein   1322
116        like    519
65      fitness    458
521         gym    388
187         get    343
646     workout    320
460    proteína    290
49       powder    245
1084       time    238
140       today    224
112   nutrition    208
1985   academia    202
1101        new    199
1155   training    197
662     isolate    194
1097     people    191
571         dey    191